name: stack_board
description: A Flutter package of stack board, components that can be stacked and edited for any widget.
version: 0.2.6+1
homepage: https://github.com/fluttercandies/stack_board

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.11.0
  flutter_drawing_board: ^0.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: